### ISSUE TITLE
Add referral code system to HSReplay.net

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#293]
This is done, once we have:
- [ ] a way to attribute purchases to an individual referrer
- [ ] a specific url or url convention to mark a session as referred
- [ ] compensation for referrers based on the amount of referrals

**Comment by beheh** [comment]
Moving to HearthSim/Company-Tracker#252.
