### ISSUE TITLE
Redesign the deck tracker download page

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#761]
- [ ] Define features that are in-line with messaging to our specific personas
- [ ] Do design with Nick
- [ ] Review Design with the Team
- [ ] Create stories in the backlog
