### ISSUE TITLE
Partner stats API endpoint: Cards

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#862]
As an HSReplay.net partner, I need an API endpoint I can access that provides the data described in the Cards section of the Partner stats API document, so that I can render reports and visualizations that include HSReplay.net data about Hearthstone cards.

## Completion requirements
- [x] A version of HSReplay.net featuring a partner cards stats API endpoint as described in the documentation is in production
- [x] There are unit tests for any new code required to implement the endpoint, and at least one integration test which will break and block a deploy if the API cannot return the expected response body.
- [x] Access to the endpoint requires an OAuth 2.0 access token with assigned scope "stats.partner:read"
- [x] ~~The endpoint enforces a provisional request limit of no more than three requests within five seconds~~ Global rate limiting has been implemented

### Subtasks

- [x] Add a view handler function for the core request-response processing (incl. interactions with hsredshift query system)
- [x] Annotate view with permissions decoration
- [x] Create a Serializer implementation for Archetype API response
- [x] Write unit tests for handler and serializer(s)
- [x] Pin data formats in hsredshift with unit tests
- [x] Write test client to exercise Archetype API endpoint to act as a smoke test
- [x] Create a cronned Jenkins job to orchestrate test client
- [x] Instrument invocation count and error count by partner application name into Influx

**Comment by beheh** [comment]
I added a test for the `card_included_popularity_report`, so this should be good.
