### ISSUE TITLE
Partner stats API endpoint: Archetypes

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#864]
As an HSReplay.net partner, I need an API endpoint I can access that provides the data described in the Archetypes section of the [Partner stats API document](https://hearthsim.atlassian.net/wiki/spaces/IN/pages/4816899/DRAFT+Partner+stats+API+documentation), so that I can render reports and visualizations that include HSReplay.net data about Hearthstone archetypes.

## Completion criteria
- [x] A version of HSReplay.net featuring a partner archetype stats API endpoint as described in the documentation is in production
- [x] There are unit tests for any new code required to implement the endpoint, and at least one integration test which ~~will break and block a deploy if the API cannot return the expected response body~~ we decided this does more harm than good. Instead a smoke test is running every 10 minutes verifying the payload.
- [x] Access to the endpoint requires an OAuth 2.0 access token with assigned scope "stats.partner:read"
- [x] ~~The endpoint enforces a provisional request limit of no more than three requests within five seconds~~ Rate limiting will be implemented globally.

### Subtasks

- [x] Add a view handler function for the core request-response processing (incl. interactions with hsredshift query system)
- [x] Annotate view with permissions decoration
- [x] ~~Annotate view with rate-limiting decoration~~ We have global rate limiting
- [x] Create a Serializer implementation for Archetype API response
- [x] Write unit tests for handler and serializer(s)
- [x] Pin data formats in hsredshift with unit tests
- [ ] ~~Propose a docstring parser / API generator to the team (http://www.django-rest-framework.org/topics/documenting-your-api/)~~ Splitting up documentation seem counter productive
- [ ] ~~Port documentation from Archetype API in design document into source code as docstring~~ Splitting up documentation seem counter productive
- [x] Write test client to exercise Archetype API endpoint to act as a smoke test
- [x] Create a cronned Jenkins job to orchestrate test client
- [x] Instrument invocation count and error count by partner application name into Influx

**Comment by joolean** [comment]
Subtasks:

- [ ] Add a view handler function for the core request-response processing (incl. interactions with hsredshift query system)
- [ ] Annotate view with permissions and rate-limiting decoration
- [ ] Create a Serializer implementation for Archetype API response
- [ ] Write unit tests for handler and serializer(s)
- [ ] Pin data formats in hsredshift with unit tests
- [ ] Propose a docstring parser / API generator to the team (http://www.django-rest-framework.org/topics/documenting-your-api/)
- [ ] Port documentation from Archetype API in design document into source code as docstring
- [ ] Write test client to exercise Archetype API endpoint to act as a smoke test
- [ ] Create a cronned Jenkins job to orchestrate test client

**Comment by azeier** [comment]
Metrics are now available here: https://metrics.hearthsim.net/d/000000017/hsreplay-net-http?orgId=1&panelId=28&fullscreen

**Comment by beheh** [comment]
I think this is done?
