### ISSUE TITLE
Implement premium redesign

### ISSUE THREAD

**Issue by azeier** [HearthSim/HSReplay.net#893]
### Premium page
![image](https://user-images.githubusercontent.com/7737910/42353198-e7cc2930-8073-11e8-9697-d73d4f56fc60.png)

### Premium modal
![image](https://user-images.githubusercontent.com/7737910/42353172-c114de36-8073-11e8-8398-a39cd22e34be.png)

## Additonal notes
- The bottom stripe panel is missing from the premium page design.
- The testimonial panel at the bottom of the premium page is a carousel.
- The premium modal has a different text and image depending on where it was opened from on the site.
- Clicking subscribe in the modal brings up the stripe dialog in a new or the same dialog.

## Prerequisites
- [x] All the required assets have been made available.

## Completion criteria
- [x] The current premium page has been redesigned to look like the "Premium page" design.
- [x] The premium modal has been redesigned to look like the "Premium modal" designs.
- [x] The premium modal is context aware (i.e. shows "rank & region" description if rank or region filter has been clicked).
- [x] Premium tabs open the modal for non premium users.
- [x] The refer a friend system has been ported over to the new page.
- [x] The smoke tests have been updated.

**Comment by azeier** [comment]
This is done and available behind the `new-premium` feature.

I'm going to leave it behind that feature at least until tomorrow so we can get some internal last minute feedback in.

## Todo after we make this public
- [ ] Drop and delete `new-premium` feature
- [ ] Drop unused code in `PremiumDetail.tsx` (`renderOld()`)
- [ ] Drop unused code in `PremiumModal.tsx` (`renderOld()`)
- [ ] Drop unused css in `premium.scss`
