### ISSUE TITLE
"Real-time" meta

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#963]
As an HSReplay.net Premium user preparing for a play session on the ladder, I want to see the effective winrates on the "Meta" page adjusted for archetype popularity within the last hour, so that I can choose an archetype to play that will be more competitive against the decks being played right now.

It should be possible to do this by adding a "LAST_HOUR" value to the `TimeRange` enum in `hsredshift.analytics.filters` and having `archetype_popularity_distribution_stats` support it.

This story is complete when:
- [ ] There is a new filter option "Last Hour" listed in the "Time Frame" menu on the left rail of the "Meta" page, which limits the popularity data to the most recent hour's worth of data we've processed
- [ ] The filter is available to Premium users; it displays grayed-out to Free users, along with the other time frame filters; the visibility of the filter is controlled by a feature tag
- [ ] The winrates on the "Tier List," "By Class," "Matchups," and "Popularity" tabs are scaled correctly when the filter is selected
- [ ] The behavior of the filter is covered by frontend unit tests
- [ ] Use of the filter is instrumented via InfluxDB so that we can measure its popularity with Premium users

**Comment by beheh** [comment]
This story is not possible using the proposed strategy. The `TimeRange` enum works against the (indexed) `game_date` column which exists on nearly all tables (as `DATE`). Building an hour-by-hour filter would require adding a datetime to all tables and queries, which significantly increases the scope.
