### ISSUE TITLE
De-duplicate replays submitted by Arcane Tracker

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#977]
As a stakeholder in the data infrastructure that supports HSReplay.net, I want to be able to unambiguously and uniquely identify games referred to by replays submitted through Arcane Tracker, so that I can avoid loading duplicate game data into our Redshift warehouse and PostgreSQL database.

At the moment, the dimensions that we use to identify a game referred to by a replay submitted via HDT (game handle, server IP, player 1 account lo, player 2 account lo) are not available when we're examining a replay submitted via Arcane Tracker. So we treat all Arcane Tracker replays as referring to games we've never seen before - a fresh copy of them always get loaded into Redshift, even when the other player may have submitted a replay via HDT. This will present a big problem once more players begin to submit replays via Arcane Tracker!

Our propose solution is to change the way game digests are generated to include fields available via a wider array of replay channels. Here's a digest structure proposed by @azeier: 
```
{p1_lo}-{p2_lo}-{hash(p1 entity id draw seq, p2 entity id draw seq, p1 hero health sequence, p2 hero health sequence)}
```

This story is complete when:
- [ ] We've added instrumentation to support the following new panels on the "Lambda" dashboard in Grafana:
  - [ ] Upload count broken down by deck tracker user agent
  - [ ] Number of replays matched to existing games broken down by deck tracker user agent
- [ ] There is a version of the upload processing Lambda function in production that generates digests in the format described above
- [ ] We've added unit test coverage, with a particular focus on ensuring that the new digests do not accidentally collide with the existing digests or themselves
